name: Build and Test
on:
  push:         
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
        with:
          ros2-distro: rolling

