name: Build and Test
on:
  push:         
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Building and testing
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          ros2-distro: rolling
